### ISSUE TITLE
Scalability and Video Call

### ISSUE THREAD

**Issue by j-planet** [roman01la/react-webrtc#1]
Hello,

First of all, thanks a lot for writing this awesome package. It seems hopeful in making life easier for creating reactjs video chat applications.

There are a few issues though:
- (Probably the **most import**) As you mentioned this is a WIP, could you please please get video chat working? Or perhaps point to some other demo/lib that does this?
- How scalable is this package? Is it feasible to use it for, say, 100 concurrent one-to-one video chats?

Many thanks and looking forward to your reply. :)
JJ

**Comment by roman01la** [comment]
Hello. Thanks! Looks like I have to check DNS records of the website :)

But you can clone this repo, install dependencies and run included example with `npm start`.
About scalability: this component was made for fun but it is just a component wrapper on top of PeerJS http://peerjs.com/ library. You probably want to check how does this library itself perform at scale.

I hope this is helpful.

**Comment by roman01la** [comment]
@jennyyuejin Demo is online again http://demo.romanliutikov.com/react-webrtc/

**Comment by j-planet** [comment]
Thanks, Roman!
Is there any plan in the pipes for adding a video chat component to this?

**Comment by roman01la** [comment]
I don't use it, so probably not. But contribution is definitely welcomed!

**Comment by j-planet** [comment]
I'm relatively new to react. But I'd love to share my work once I figure it out.
